# Theming
include ~/.local/state/quickshell/user/generated/terminal/kitty-theme.conf

# ── Styling ───────────────────────────────────────────────────────────

# Font
font_family 			Fira Code
font_size 			12

# Padding
window_padding_width 		5

tab_bar_style 			hidden

# Use fish shell
shell 				zsh

# Copy
map ctrl+c    			copy_or_interrupt

# Opacity
dynamic_background_opacity 	yes
background_opacity 		0.9
background_blur 		64

# ── Misc ──────────────────────────────────────────────────────────────
enable_audio_bell           	no
confirm_os_window_close 	0

# ── Mappings ──────────────────────────────────────────────────────────
map page_up    			scroll_page_up
map page_down    		scroll_page_down

map ctrl+plus  			change_font_size all +1
map ctrl+minus 			change_font_size all -1
map ctrl+equal 			change_font_size all 0

# Set opacity to 1 (opaque)
map ctrl+shift+u 		set_background_opacity 0.9

# Set opacity to 0.85 (transparent)
map ctrl+shift+t 		set_background_opacity 1
