# TODO: have fun there: https://github.com/rothgar/awesome-tmux?search=1
source-file ~/.config/tmux/keybinds.conf
source-file ~/.config/tmux/options.conf
source-file ~/.config/tmux/plugins.conf

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
