# MONITOR CONFIG
# monitor=,preferred,auto,1

# eDP = in-built monitor (X1 laptop)
monitor=eDP-1,2880x1800@90,0x0,1.33 # Principal monitor

# Monitors from home
# monitor=HDMI-A-1,preferred,0x0,1 # Widescreen

# Monitors at work
monitor=DP-3,2560x1440@60 ,0x0, 1 # Widescreen
monitor=DP-4,2560x1440@60 ,-2560x0,1 # -2560x0 => to the left

