# ── Apps ────────────────────────────────────────────────────────────────────
# $menu           = wofi --show drun --location=center
# $run            = wofi --show run --location=top --width=100%
# $terminal       = kitty --config $HOME/.config/kitty/kitty.conf

# vim: ft=hyprlang
