unbind r
bind r source-file ~/.tmux.conf

set -g prefix M-w # leader key

# Vim keybinding for moving from pane to pane
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Keybind to resize panes
bind-key -r -n M-K resize-pane -U 5 # Resize pane up using Alt+Shift+k
bind-key -r -n M-J resize-pane -D 5 # Resize pane down using Alt+Shift+j
bind-key -r -n M-H resize-pane -L 5 # Resize pane left using Alt+Shift+h
bind-key -r -n M-L resize-pane -R 5 # Resize pane right using Alt+Shift+l

# Set default-path for new panes
bind-key C set-option -g default-path "#{pane_current_path}"

# Split comment H && V
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# Move to prev || next windows
# Bind Alt+h to previous window and Alt+l to next window
bind-key -n M-h previous-window
bind-key -n M-l next-window

# Rename session
bind . command-prompt -I "#S" "rename-session '%%'"
bind , command-prompt -I "#W" "rename-window '%%'"
# Rename window

# Choose session
bind-key f choose-session

# Unbinds
unbind '"'
unbind %
unbind-key n
unbind-key p
unbind $

# vim: ft=tmux
