set-environment -g PATH "/usr/local/bin:/bin:/usr/bin"

set-option -g repeat-time 1000
set-option -g status-position top
set-option -g allow-rename on # don't rename windows automatically

# Allow mouse use
set -g mouse on

# Enable true colors for nvim
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Allow images 
set -gq allow-passthrough on
set -g visual-activity off

set -g status-bg default
# vim: ft=tmux
