# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin "janoamaral/tokyo-night-tmux"
# set -g @plugin 'TechnicalDC/tmux-pywal-theme'

# note: always load tmux=continuum last or at least after a color scheme
# source: https://github.com/tmux-plugins/tmux-continuum/issues/48#issuecomment-603147319
set -g @plugin 'tmux-plugins/tmux-continuum' # autosave



## Tmux resurrect settings
set -g @resurrect-save 'on' # Save when tmux is closed
set -g @resurrect-save 'S'
set -g @resurrect-restore 'R'
set -g @resurrect-capture-pane-contents 'on'

## Continuous save + auto resurrect
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

### No longer unsed plugins ###

# set -g @plugin 'catppuccin/tmux'
# Catppuccin settings
#set -g @catppuccin_flavour 'macchiato' # latte, frappe, macchiato, mocha
#
#set -g @catppuccin_window_left_separator "█"
#set -g @catppuccin_window_right_separator "█ "
#set -g @catppuccin_window_number_position "right"
#set -g @catppuccin_window_middle_separator " | "
#set -g @catppuccin_window_default_fill "none"
#
#set -g @catppuccin_window_current_fill "all"
#set -g @catppuccin_window_current_color "#7dc4e4"
#
#set -g @catppuccin_status_modules_right "application session host date_time"
#set -g @catppuccin_status_left_separator "█"
#set -g @catppuccin_status_right_separator "█ "
#set -g @catppuccin_status_connect_separator "no"
#
#set -g @catppuccin_date_time_text "%d-%m %H:%M"
#
#set -g @catppuccin_window_default_text "#W"
#set -g @catppuccin_window_current_text "#W"
#run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# vim: ft=tmux
